name: test

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  test:
    name: pytest (${{ matrix.os }}, ${{ matrix.python-version }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest"]   #, "windows-latest"]
        python-version: ["3.6", "3.7", "3.8"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install miniconda
        uses: conda-incubator/setup-miniconda@v1
        with:
          mamba-version: "*"
          channels: conda-forge,defaults
          channel-priority: true
      - name: Conda info
        shell: bash -l {0}
        run: conda info
      - name: Install dependencies (mamba)
        shell: bash -l {0}
        run: |
          mamba install xarray ipygany ipywidgets pytest pytest-cov
      - name: Install ipyfastscape
        shell: bash -l {0}
        run: |
          pip install --no-deps -e .
          python -c "import ipyfastscape"
      - name: Run tests
        shell: bash -l {0}
        run: pytest src/ipyfastscape --cov=src/ipyfastscape --cov-report term-missing --cov-report xml --verbose --color=yes
